language: cpp
git:
  submodules: false
before_script:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- cd A-03
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T Allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ugwyn0431:$BINTRAY_API_KEY "https://api.bintray.com/content/gwyn0431/OTUS_CPP/A-03/$TRAVIS_BUILD_NUMBER/Allocator_0.0.$TRAVIS_BUILD_NUMBER.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
